# Generated by Django 3.2.9 on 2021-12-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Open Answer', 'Open Answer')], default='Normal', max_length=50),
        ),
    ]
