# Generated by Django 3.2.9 on 2021-12-02 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servey',
            name='patricipants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
