# Generated by Django 3.2.9 on 2021-12-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_rename_servey_survey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortOption',
            new_name='Option',
        ),
        migrations.DeleteModel(
            name='OpenOption',
        ),
    ]
