# Generated by Django 3.2.9 on 2021-12-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20211202_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
